### PR TITLE
Localization related updates to the de_DE po and mo files

### PR DESCRIPTION
**Pull request by rpkoller**
- Made the plugin description available for translation
- Excluded the assets folder as SearchPath (The folder contains no PHP files relevant for translation at all) 
- Added a tiny typo fix for the English plugin description

### CODE REVIEW

**Comment by Zodiac1978** [comment]
Thanks for your help @rpkoller. Much appreciated!

**Comment by rpkoller** [comment]
yw. But please also check the second pull request. I've initially thought the translation already worked and commited. But when i've rechecked afterwards in my test install the plugin was still showing the english description. ;) On a recheck i've noticed that the domain path was missing in the plugin description. sorry.

**Comment by Zodiac1978** [comment]
It was working if the plugin is active. The Domain Path is necessary to have the translation also be used for the inactive plugin. Second pull request is merged now too and everything is working fine. 1.0 milestone is near! :)

**Comment by rpkoller** [comment]
Ahhhhhhh didn't knew that. And i was checking if the localization of the plugin description was working while the plugin was inactive. Cool learned something new again. ;) thanks!

**Comment by Zodiac1978** [comment]
Learned this today, too! :)

**Pull request merged**
